export const lightTheme = {
  container: {
    flexGrow: 1,
    backgroundColor: "#f2f2f7",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  input: {
    width: "90%",
    height: 40,
    borderRadius: 15,
    paddingLeft: 10,
    marginBottom: 15,
    backgroundColor: "#e3e3e8",
    color: "#000000",
    fontSize: 17,
  },
  map: {
    width: "100%",
    height: 300,
    marginBottom: 10,
  },
  text: {
    fontSize: 20,
    marginBottom: 5,
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    color: "#000000",
    fontWeight: "bold",
  },
  loadingThrobber: {
    marginTop: 10,
    marginBottom: 10,
  },
  addCarButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#efeeef",
    padding: 10,
    borderRadius: 150,
    marginBottom: 10,
    marginHorizontal: 5,
  },
  carListButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#efeeef",
    padding: 10,
    borderRadius: 150,
    marginBottom: 10,
    //marginHorizontal: 5,
  },
  buttonText: {
    color: "#007afe",
    fontWeight: "bold",
    marginLeft: 7,
    fontSize: 16,
  },
  saveButton: {
    flexDirection: "row",
    backgroundColor: "#efeeef",
    padding: 12,
    borderRadius: 150,
    alignItems: "center",
    marginTop: 20,
  },
  saveButtonText: {
    color: "#007afe",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 10,
  },
  deleteCarButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1c1c1e",
    padding: 10,
    borderRadius: 100,
    marginBottom: 10,
    //marginHorizontal: 5,
  },
  deleteImageButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1c1c1e",
    padding: 10,
    borderRadius: 150,
    marginBottom: 10,
    marginHorizontal: 5,
  },
  deleteButtonText: {
    color: "#ff3c31",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 7,
  },
  clearButton: {
    marginLeft: 5,
  },
  disabledButton: {
    backgroundColor: "#1c1c1e",
  },
  disabledButtonText: {
    color: "#86858a",
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 10,
    marginBottom: 1,
  },
};
