export const darkTheme = {
  tabBarActiveTintColor: "#3b82f7",
  tabBarInactiveTintColor: "#818181",
  tabBarBackgroundColor: "#1c1c1e",
  tabBarBorderWidth: 0,
  headerBackgroundColor: "#1c1c1e",
  headerTextColor: "#ffffff",
  statusBarStyle: "light",
  backgroundColor: "#000000",
  pickerColor: "#ffffff",
  thumbColor: "#ffffff",
  trackColor: "#39393d",
  closeIconColor: "#98989e",
  searchIconColor: "#98979e",
  placeholderTextColor: "#98989e",

  searchIcon: {
    marginRight: 5,
  },
  addCarContainer: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  carListContainer: {
    flex: 1,
    backgroundColor: "#000000",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    width: "90%",
    backgroundColor: "#1c1c1e",
    marginBottom: 10,
    marginTop: 10,
    borderRadius: 15,
    paddingHorizontal: 10,
    height: 40,
  },
  searchInput: {
    flex: 1,
    fontSize: 17,
    color: "#FFFFFF",
  },
  settingsContainer: {
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    width: "90%",
    backgroundColor: "#1c1c1e",
    marginBottom: 10,
    marginTop: 10,
    borderRadius: 15,
    paddingHorizontal: 10,
    height: 40,
  },
  input: {
    flex: 1,
    fontSize: 17,
    color: "#FFFFFF",
    backgroundColor: "#1c1c1e",
  },
  map: {
    width: "100%",
    height: 300,
    marginBottom: 10,
  },
  card: {
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    borderWidth: 0.8,
    borderColor: "#313134",
    borderRadius: 25,
    backgroundColor: "#000000",
  },
  settingsCard: {
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    width: "90%",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#1c1c1e",
  },
  carListMap: {
    width: "100%",
    height: 250,
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  settingsTitle: {
    fontSize: 24,
    marginTop: 10,
    marginBottom: 10,
    color: "#ffffff",
    fontWeight: "bold",
  },
  addCarText: {
    fontSize: 20,
    marginBottom: 5,
  },
  emptyListText: {
    fontSize: 16,
    textAlign: "center",
    marginTop: 5,
    color: "#FFFFFF",
  },
  carListText: {
    fontSize: 16,
    marginBottom: 5,
    color: "#8b8b90",
    fontWeight: "bold",
  },
  imageText: {
    fontSize: 16,
    marginBottom: 5,
    textAlign: "center",
    color: "#8b8b90",
  },
  carText: {
    fontSize: 22,
    marginBottom: 5,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  carImage: {
    width: "100%",
    height: 300,
    marginVertical: 10,
  },
  carListLoadingThrobber: {
    alignSelf: "center",
    marginVertical: 250,
  },
  loadingThrobber: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -15,
    marginLeft: -15, 
  },
  imageThrobber: {
    marginTop: 10,
  },
  picker: {
    width: "80%",
    color: "#ffffff",
    backgroundColor: "#1c1c1e",
    borderRadius: 15,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 10,
    marginBottom: 1,
  },
  addCarButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1c1c1e",
    padding: 10,
    borderRadius: 150,
    marginBottom: 10,
    marginHorizontal: 5,
  },
  carListButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1c1c1e",
    padding: 10,
    borderRadius: 150,
    marginBottom: 10,
    //marginHorizontal: 5,
  },
  buttonText: {
    color: "#3b82f7",
    fontWeight: "bold",
    marginLeft: 7,
    fontSize: 16,
  },
  saveButton: {
    flexDirection: "row",
    backgroundColor: "#1c1c1e",
    padding: 12,
    borderRadius: 150,
    alignItems: "center",
    marginTop: 20,
  },
  saveButtonText: {
    color: "#007aff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 10,
  },
  deleteCarButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1c1c1e",
    padding: 10,
    borderRadius: 100,
    marginBottom: 10,
    //marginHorizontal: 5,
  },
  deleteImageButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1c1c1e",
    padding: 10,
    borderRadius: 150,
    marginBottom: 10,
    marginHorizontal: 5,
  },
  deleteButtonText: {
    color: "#ff3b30",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 7,
  },
  clearButton: {
    marginLeft: 5,
  },
  disabledButton: {
    backgroundColor: "#1c1c1e",
  },
  disabledButtonText: {
    color: "#818181",
  },
};
