export const lightTheme = {
  tabBarActiveTintColor: "#007afe",
  tabBarInactiveTintColor: "#979797",
  tabBarBackgroundColor: "#ffffff",
  tabBarBorderWidth: 1,
  headerBackgroundColor: "#ffffff",
  headerTextColor: "#000000",
  statusBarStyle: "dark",
  backgroundColor: "#f2f2f7",
  pickerColor: "#000000",
  thumbColor: "#ffffff",
  trackColor: "#39393d",
  addCarContainer: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  carListContainer: {
    flex: 1,
    backgroundColor: "#f2f2f7",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    width: "90%",
    backgroundColor: "#e3e3e8",
    marginBottom: 10,
    marginTop: 10,
    borderRadius: 15,
    paddingHorizontal: 10,
    height: 40,
  },
  settingsContainer: {
    backgroundColor: "#f2f2f7",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  input: {
    width: "90%",
    height: 40,
    borderRadius: 15,
    paddingLeft: 10,
    marginBottom: 15,
    backgroundColor: "#e3e3e8",
    color: "#000000",
    fontSize: 17,
  },
  searchInput: {
    flex: 1,
    fontSize: 17,
    color: "#000000",
    backgroundColor: "#e3e3e8",
  },
  map: {
    width: "100%",
    height: 300,
    marginBottom: 10,
  },
  carListMap: {
    width: "100%",
    height: 250,
    marginBottom: 20,
  },
  card: {
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    borderRadius: 25,
    backgroundColor: "#ffffff",
  },
  settingsCard: {
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    width: "90%",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#ffffff",
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    color: "#000000",
    fontWeight: "bold",
  },
  settingsTitle: {
    fontSize: 24,
    marginTop: 10,
    marginBottom: 10,
    color: "#000000",
    fontWeight: "bold",
  },
  addCarText: {
    fontSize: 20,
    marginBottom: 5,
  },
  emptyListText: {
    fontSize: 16,
    textAlign: "center",
    marginTop: 5,
    color: "#000000",
  },
  carListText: {
    fontSize: 16,
    marginBottom: 5,
    color: "#858593w",
  },
  imageText: {
    fontSize: 16,
    marginBottom: 5,
    textAlign: "center",
    color: "#8b8b90",
  },
  carText: {
    fontSize: 22,
    marginBottom: 5,
    fontWeight: "bold",
    color: "#000000",
  },
  loadingThrobber: {
    marginTop: 10,
    marginBottom: 10,
  },
  carImage: {
    width: "100%",
    height: 300,
    marginVertical: 10,
  },
  bigThrobber: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  carListLoadingThrobber: {
    alignSelf: "center",
    marginVertical: 10,
  },
  picker: {
    width: "80%",
    color: "#ffffff",
    backgroundColor: "#ffffff",
    borderRadius: 15,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 10,
    marginBottom: 1,
  },
  addCarButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e3e3e8",
    padding: 10,
    borderRadius: 150,
    marginBottom: 10,
    marginHorizontal: 5,
  },
  carListButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eeeef0",
    padding: 10,
    borderRadius: 150,
    marginBottom: 10,
    //marginHorizontal: 5,
  },
  buttonText: {
    color: "#007afe",
    fontWeight: "bold",
    marginLeft: 7,
    fontSize: 16,
  },
  saveButton: {
    flexDirection: "row",
    backgroundColor: "#e3e3e8",
    padding: 12,
    borderRadius: 150,
    alignItems: "center",
    marginTop: 20,
  },
  saveButtonText: {
    color: "#007afe",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 10,
  },
  deleteCarButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eeeef0",
    padding: 10,
    borderRadius: 100,
    marginBottom: 10,
    //marginHorizontal: 5,
  },
  deleteImageButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eeeef0",
    padding: 10,
    borderRadius: 150,
    marginBottom: 10,
    marginHorizontal: 5,
  },
  deleteButtonText: {
    color: "#ff3b30",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 7,
  },
  clearButton: {
    marginLeft: 5,
  },
  disabledButton: {
    backgroundColor: "#e3e3e8",
  },
  disabledButtonText: {
    color: "#98989e",
  },
};
